### ISSUE TITLE
SharpDirect3D12.IsSupported needs to release nativePtr

### ISSUE THREAD

**Issue by h1cks** [amerkoleci/SharpWindows#2]
Ran the HelloDirect3D12 example, was failing when creating the device.  Checked the code, found that the IsSupported function was failing to release the native ptr.

Added the following code.

`          var device = new ID3D12Device(nativePtr);

                device.Dispose();`

Have created a pull request in regards to IsSupported.

**Comment by amerkoleci** [comment]
I fixed this locally, will commit later.

**Comment by amerkoleci** [comment]
This is fixed in last alpha06
